# Configuration of the Chairs plugin for Craftbukkit
# ------
# A list of all compatible block and item names: http://bit.ly/AmJgMb.
# ------
# allowed-blocks: Set the blocks you want to be able to sit down on. Use descriptive name or item ID. Use name:number to set sitting height.
# auto-rotate: If set to true, you are automatically rotated to the descending face of the stairs-block when sitting down.
# sneaking: If set to true, you have to sneak to sit down on a chair.
# max-chair-width: Define how many blocks a chair can be long (set to number <= 0 for unlimited width).
# sign-check: If set to true, you will only be able to sit down when there are signs on both of the ends of the chair.
# distance: The maximum distance between the chair (the center of the block) and the player to be able to sit down (to prevent glitching through walls, etc.).
# sitting-height: Set how high you are sitting 'in' the stairs block (default is 0.7).
# sitting-height-adj: Non-stairs and non-steps are adjusted automatically by this amount.
# upsidedown-check: If true then prevent players from sitting on upside down stairs.
# seat-occupied-check: Check if seat is already occupied.
# per-item-perms: Enable chairs.sit.[item] permission node. Set to false if you're sitting on every block.
# ignore-if-block-in-hand: Set this true disable sititng if player is holding a block in hand.
# ------
allowed-blocks:
    - WOOD_STAIRS
    - SPRUCE_WOOD_STAIRS
    - JUNGLE_WOOD_STAIRS
    - BIRCH_WOOD_STAIRS
    - SANDSTONE_STAIRS
    - COBBLESTONE_STAIRS
    - BRICK_STAIRS
    - SMOOTH_STAIRS
    - NETHER_BRICK_STAIRS
    - QUARTZ_STAIRS
valid-signs:
  - SIGN
  - WALL_SIGN
  - SIGN_POST
  - ITEM_FRAME
auto-rotate: true
sneaking: true
max-chair-width: 3
sign-check: false
distance: 2
sitting-height: 0.7
sitting-height-adj: 1.0
permissions: true
notify-player: true
upside-down-check: true
seat-occupied-check: true
upper-step-check: true
per-item-perms: true
ops-override-perms: false
ignore-if-block-in-hand: false
sit-effects:
  enabled: false
  interval: 20
  healing:
    amount: 1
    max-percent: 100
messages:
  sitting: '&7You are now sitting.'
  standing: '&7You are no longer sitting.'
  occupied: '&7This seat is occupied by &6%PLAYER%&7!'
  reloaded: 'Chairs configuration reloaded.'
  no-permission: '&cYou do not have permission to do this!'
  enabled: '&7You have enabled chairs for yourself!'
  disabled: '&7You have disabled chairs for yourself!'
    